- hosts: client
  become: true # become root
  roles:
    - common
    - rathole
    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
        tailscale_args: "--ssh"

- hosts: server
  become: true # become root
  roles:
    - system
    - common
    - rathole
    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
        tailscale_args: "--ssh"
