---
## https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_vars_facts.html#local-facts

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install/update aptitude package manager
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Install dependencies
  apt:
    pkg:
      - unzip
    state: latest
    update_cache: true
