---
# https://docs.pivpn.io/wireguard/

- name: Check if pivpn is installed
  stat:
    path: /etc/pivpn/wireguard/setupVars.conf
  register: pivpn_result

- name: Download latest pivpn version
  get_url:
    force: false # Force the file to be re-downloaded even if it exists.
    dest: /tmp/install-pivpn.sh
    url: https://install.pivpn.io
    mode: +x
  when: not pivpn_result.stat.exists

- name: Copy pivpn config
  copy:
    src: wireguard.conf
    dest: /tmp/wireguard.conf
    remote_src: false
    force: true # force the file to be replaced
  when: not pivpn_result.stat.exists


- name: Execute PIVPN install
  ansible.builtin.shell:
    cmd: /tmp/install-pivpn.sh --unattended /tmp/wireguard.conf
  register: pivpn_install
  when: not pivpn_result.stat.exists

- name: Rebooting to apply pivpn changes
  ansible.builtin.reboot:
  when: pivpn_install is defined