---
- name: Download latest pivpn version
  get_url:
    force: false # Force the file to be re-downloaded even if it exists.
    dest: /tmp/install-pivpn.sh
    url: https://install.pivpn.io
    mode: +x
  tags: install

- name: Copy pivpn config
  copy:
    src: pivpn.conf
    dest: /tmp/pivpn-setup.conf
    remote_src: false
    force: true # force the file to be replaced on subsequent runs
  tags: install

# https://docs.pivpn.io/wireguard/
- name: Execute PIVPN unattended install, log will be generated at /tmp/install-pivpn-output.log
  ansible.builtin.shell: /tmp/install-pivpn.sh --unattended /tmp/pivpn-setup.conf >> /tmp/pivpn-installer-output.log
